package org.singsurf.singsurf.acurve;

/**
 * Exceptions generated by ASurf and ACurve clients
 */
public class AsurfException extends Exception {

	public AsurfException(String string) {
		super(string);
	}

	private static final long serialVersionUID = 1L;

}
